name: data_sheet
description: Data table with in-cell-edit, scroll, with callback feature for select-rows, sort,  update and custom-contents
version: 0.0.4
homepage: https://github.com/sanjay888/data_sheet
repository: https://github.com/sanjay888/data_sheet

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

platforms:
  android:
  ios:
  web:
  windows:

screenshots:
  - description: 'Fixed Column Widths'
    path: screenshots/FixedWidth.png
  - description: 'Column Widths in Pixels'
    path: screenshots/PixelWidth.png
  - description: 'Column Width Proportionate to Widget Width'
    path: screenshots/ratioWidth.png
  - description: 'Scroll sample'
    path: screenshots/scroll.gif
  - description: 'Sort sample'
    path: screenshots/sort.gif
  - description: 'Select sample'
    path: screenshots/select.gif

dependencies:
  date_field: ^3.0.5
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

linter:
    rules:
      - public_member_api_docs
      - package_api_docs

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
